Wrote specs.md
Uni-Sopron/prog1-24t-beadando-dorinatirpak pull request #2
Opened 2024-05-27 13:24 UTC by dorinatirpak

2024-05-30 12:27 UTC, oliverosz requested changes

2024-05-30 12:27 UTC, oliverosz commented on specification.md
> +- Delete book: Deletes the book and all its data (from "Title" to "Publication")
```suggestion
```

2024-05-30 12:27 UTC, oliverosz commented on specification.md
> +At this choice, a menu will appear where the user have to select which data of the book they want to edit, e.g.: ("Author", "Page count", etc.) Once the data has been edited, the program will return
> the book

Which book?

Both of these should start with a search step where the user can filter the book list, then select the one to edit/delete.

2024-05-30 12:27 UTC, oliverosz commented on specification.md
> +**The csv file contains incorrect data, which will be ignored by the program.**
```suggestion
**The csv file may contain invalid data, which will be ignored by the program.**
```
(Incorrect means factually untrue, which the program cannot check.)

2024-05-30 12:27 UTC, oliverosz commented on specification.md
> +Based on a menu you can choose between "Admin mode", "Graph" and "Exit" options (1-3)
Add a "Reader" mode, where the user first selects one of the previously created reading lists (scan their storage directory for existing lists), or creates a new list.
Then in the menu:
- Print reading list
- Add book to list
- Remove book from list
- Delete list

2024-05-30 12:27 UTC, oliverosz commented on specification.md
> +The graphs can be plotted using command line arguments. Each bar will display a graph showing how many items are in a given category.
If they are set by command line arguments, the main menu should not have a "Graph" option. If a graph argument is given, show the graphs and exit, if not given, enter main menu.

2024-05-30 12:27 UTC, oliverosz commented on specification.md
> +"-pn" "--publication"
Add a `-r --reader name` option to specify a reading list, so the chart will only include books from that list.

2024-05-31 13:48 UTC, oliverosz requested changes

2024-05-31 13:48 UTC, oliverosz commented on books.csv
> +,title,author,price,publisher,page_count,genre,publication_year
```suggestion
id,title,author,price,publisher,page_count,genre,publication_year
```

2024-05-31 13:48 UTC, oliverosz commented on specification.md
> +"-pn" "--publication"
Az, hogy 10, 100, vagy 1000 sora van a táblázatnak, az nem befolyásolja a program bonyolultságát. Nyilván 20-nál több lesz, tehát szükség van a szűrési, keresési műveletekre. Fejlesztés közbeni teszteléshez lehet érdemes használni egy kisebb fájlt, de az 1000 sorossal is működnie kell a véglegesnek.

Viszont az még kevés, hogy egy CSV-t tud beolvasni, megjeleníteni, szűrni, meg szerkeszteni a user. Valami funkcionalitás legyen még. Azért javasoltam, hogy legyen több felhasználó, akik saját listákat tudnak létrehozni, szerkeszteni. Meg úgy a diagramok is érdekesebbek lesznek.

2024-05-31 18:14 UTC, dorinatirpak commented on specification.md
> +"-pn" "--publication"
> Az, hogy 10, 100, vagy 1000 sora van a táblázatnak, az nem befolyásolja a program bonyolultságát.

Persze, tudom, de akkor teszteléshez inkább egy kisebb méretű adatbázissal fogok dolgozni. 
Módosítottam a specification.md-t a javaslataid alapján, remélem így már jó lesz! És köszönöm a segítséget!

2024-06-03 16:49 UTC, dorinatirpak commented
@oliverosz Köszönöm! 
Gondoltam itt még belefér, ha nem túl részletes a commit message, de a fejlesztésnél mindenképp ügyelni fogok rá.

2024-06-08 14:58 UTC, oliverosz commented
Folytathatod a fejlesztést ezen a branchen is, csak szólok, hogy a GitHub Actions workflow csak a main branchen fut le, így most nem látod a generált dokumentációt, meg a unit tesztek eredményét GitHubon. Szerintem mergeld be a mainbe és folytasd ott.

2024-06-08 18:25 UTC, dorinatirpak commented
Köszönöm, hogy szóltál és bocsánat! 
Csak nem mertem merge-ölni, mert írtátok, hogy nem kell, és féltem, ha bármit merge-ölök, kapásból bevágjátok az elégtelent. 😅
Szóval Te most folyamatosan kaptad az értesítéseket a commitokról? Mert akkor azért is bocsánat!

2024-06-08 18:26 UTC, merged